### ISSUE TITLE
KoneXP support

### ISSUE THREAD

**Issue by magicalraccoon** [flathub/net.sourceforge.roccat.roccat-tools#1]
Please add support for KoneXP mice.

**Comment by G-Ray** [comment]
Hi @magicalraccoon !

Unfortunately the upstream project located at https://sourceforge.net/projects/roccat/ is not maintained anymore.
This flatpak is provided to offer support for legacy devices, but don't expect new devices to be added. Hopefully you might find other open source projects to configure you mouse :hugs:
