### ISSUE TITLE
Tyon flathub config tool 

### ISSUE THREAD

**Issue by woeisme** [flathub/net.sourceforge.roccat.roccat-tools#2]
I'm getting the following error when launching the Tyon Config tool 

![image](https://github.com/user-attachments/assets/5f4949fc-1e3e-47d3-a3c8-b54245ff6330)

Wondering where I can give it correct perms and also how to run the Tyon Config from CLI using flatpak

**Comment by G-Ray** [comment]
Hi @woeisme !

I guess you have added the udev rules with commands listed in the `README` ?
https://github.com/flathub/net.sourceforge.roccat.roccat-tools/blob/master/README.md

It seems someone reported a similar issue on the upstream project, you can try checking the `roccat` group: https://sourceforge.net/p/roccat/bugs/85/#b45c

Let me know if you resolved the issue :hugs:

**Comment by woeisme** [comment]
Hello @G-Ray yes I believe so, but I had not created the group like your 2nd link suggested (I wasn't sure the flatpak instructions required that). I've done so and can test when I return this week. Thanks for the help, I'll report back

**Comment by woeisme** [comment]
> Hi @woeisme !
> 
> I guess you have added the udev rules with commands listed in the `README` ? https://github.com/flathub/net.sourceforge.roccat.roccat-tools/blob/master/README.md
> 
> It seems someone reported a similar issue on the upstream project, you can try checking the `roccat` group: https://sourceforge.net/p/roccat/bugs/85/#b45c
> 
> Let me know if you resolved the issue 🤗

yup, it worked! thanks for the help!
