### ISSUE TITLE
Deprecated Runtime

### ISSUE THREAD

**Issue by Hoshi98** [flathub/net.sourceforge.roccat.roccat-tools#3]
Getting this on flatpak update:

Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   net.sourceforge.roccat.roccat-tools

**Comment by G-Ray** [comment]
Thank you @Hoshi98 !

I updated the runtime to 24.08.
Update should soon be pushed to flathub repo :tada:
